apiVersion: batch/v1
kind: Job
metadata:
  name: say-hi-job
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: sey-hi-job
    spec:
      containers:
      - name: say-hi-job
        image: 	docker-registry.default.svc:5000/********/mypy-base-image:latest
        command: ["python",  "main.py"]
      restartPolicy: OnFailure
